let questions = [
    {
        id: 1,
        question: "Wymień Parki Narodowe w Polsce.",
        avalibleAnswers: 23,
        answers: [
            'Babiogórski Park Narodowy',
            'Białowieski Park Narodowy',
            'Biebrzański Park Narodowy',
            'Bieszczadzki Park Narodowy',
            'Park Narodowy Bory Tucholskie',
            'Drawieński Park Narodowy',
            'Gorczański Park Narodowy',
            'Park Narodowy Gór Stołowych',
            'Kampinoski Park Narodowy',
            'Karkonoski Park Narodowy',
            'Magurski Park Narodowy',
            'Narwiański Park Narodowy',
            'Ojcowski Park Narodowy',
            'Pieniński Park Narodowy',
            'Poleski Park Narodowy',
            'Roztoczański Park Narodowy',
            'Słowiński Park Narodowy',
            'Świętokrzyski Park Narodowy',
            'Tatrzański Park Narodowy',
            'Park Narodowy Ujście Warty',
            'Wielkopolski Park Narodowy',
            'Wigierski Park Narodowy',
            'Woliński Park Narodowy'
        ]
    },
    {
        id: 2,
        question: "Wymień województwa w Polsce.",
        avalibleAnswers: 16,
        answers: [
            'Dolnośląski',
            'Kujawsko-Pomorskie',
            'Lubelskie',
            'Lubuskie',
            'Łódzkie',
            'Małopolskie',
            'Mazowieckie',
            'Opolskie',
            'Podkarpackie',
            'Podlaskie',
            'Pomorskie',
            'Śląskie',
            'Świętokrzyskie',
            'Warmińsko-Mazurskie',
            'Wielkopolskie',
            'Zachodniopomorskie',
        ]
    },
    {
        id: 3,
        question: "Wymień sąsiadów Polski wraz z stolicami.",
        avalibleAnswers: 7,
        answers: [
            'Niemcy - Berlin',
            'Litwa - Wilno',
            'Czechy - Praga',
            'Słowacja - Bratysława',
            'Ukraina - Kijów',
            'Białoruś - Mińsk',
            'Rosja - Moskwa'
        ]
    },
    {
        id: 4,
        question: "Wymień sąsiadów Francji.",
        avalibleAnswers: 8,
        answers: [
            'Andora',
            'Belgia',
            'Hiszpania',
            'Luksemburg',
            'Monako',
            'Niemcy',
            'Szwajcaria',
            'Włochy',
        ]
    },
    {
        id: 5,
        question: "Wymień sąsiadów Rosji.",
        avalibleAnswers: 14,
        answers: [
            'Ukraina',
            'Białoruś',
            'Polska',
            'Litwa',
            'Łotwa',
            'Estonia',
            'Finlandia',
            'Norwegia',
            'Korea Północna',
            'Chiny',
            'Mongolia',
            'Kazachstan',
            'Azerbejdżan',
            'Gruzja'
        ]
    },
    {
        id: 6,
        question: "Wymień stany w USA",
        avalibleAnswers: 51,
        answers: [
            'Alabama',
            'Alaska',
            'Arizona',
            'Arkansas',
            'Connecticut',
            'Dakota Południowa',
            'Dakota Północna',
            'Delaware',
            'Floryda',
            'Georgia',
            'Hawaje',
            'Idaho',
            'Illinois',
            'Indiana',
            'Lowa',
            'Kalifornia',
            'Kansas',
            'Karolina Południowa',
            'Karolina Północna',
            'Kentucky',
            'Kolorado',
            'Luizjana',
            'Maine',
            'Maryland',
            'Massachusetts',
            'Michigan',
            'Minnesota',
            'Missisipi',
            'Montana',
            'Nebraska',
            'Nevada',
            'New Hampshire',
            'New Jersey',
            'Nowy Jork',
            'Nowy Meksyk',
            'Ohio',
            'Oklahoma',
            'Oregon',
            'Pensylwania',
            'Rhode Island',
            'Teksas',
            'Tennessee',
            'Utah',
            'Vermont',
            'Waszyngton',
            'Wirginia',
            'Wirginia Zachodnia',
            'Wisconsin',
            'Wyoming',
            'Dystrykt Kolumbii',
        ]
    },
    {
        id: 7,
        question: "Wymień Państwa na A",
        avalibleAnswers: 15,
        answers: [
            'Afganistan',
            'Albania',
            'Algieria',
            'Andora',
            'Angola',
            'Anguilla',
            'Antigua i Barbuda',
            'Antyle Holenderskie',
            'Arabia Saudyjska',
            'Argentyna',
            'Armenia',
            'Aruba',
            'Australia',
            'Austria',
            'Azerbejdżan'
        ]
    },
    {
        id: 8,
        question: "Wymień jednoliterowe (Symbol chemiczny) pierwiastki chemiczne",
        avalibleAnswers: 14,
        answers: [
            'H - Wodór',
            'B - Bor',
            'C - Węgiel',
            'N - Azot',
            'O - Tlen',
            'F - Fluor',
            'P - Fosfor',
            'S - Siarka',
            'K - Potas',
            'V - Wanad',
            'Y - Itr',
            'I - Jod',
            'W - Wolfram',
            'U - Uran',
        ]
    },
    {
        id: 9,
        question: "Wymień państwa Europy",
        avalibleAnswers: 46,
        answers: [
            'Albania',
            'Andora',
            'Austria',
            'Belgia',
            'Białoruś',
            'Bośnia i Hercegowina',
            'Bułgaria',
            'Chorwacja',
            'Czarnogóra',
            'Czechy',
            'Dania',
            'Estonia',
            'Finlandia',
            'Francja',
            'Grecja',
            'Hiszpania',
            'Holandia',
            'Irlandia',
            'Islandia',
            'Kazachstan',
            'Liechtenstein',
            'Litwa',
            'Luksemburg',
            'Łotwa',
            'Macedonia Północna',
            'Malta',
            'Mołdawia',
            'Monako',
            'Niemcy',
            'Norwegia',
            'Polska',
            'Portugalia',
            'Rosja',
            'Rumunia',
            'San Marino',
            'Serbia',
            'Słowacja',
            'Słowenia',
            'Szwajcaria',
            'Szwecja',
            'Turcja',
            'Ukraina',
            'Watykan',
            'Węgry',
            'Wielka Brytania',
            'Włochy',
        ]
    },
    {
        id: 10,
        question: "Wymień stolice Europy",
        avalibleAnswers: 46,
        answers: [
            'Tirana',
            'Andora',
            'Wiedeń',
            'Bruksela',
            'Mińsk',
            'Sarajewo',
            'Sofia',
            'Zagrzeb',
            'Podgorica',
            'Praga',
            'Kopenhaga',
            'Tallinn',
            'Helsinki',
            'Paryż',
            'Ateny',
            'Madryt',
            'Amsterdam',
            'Dublin',
            'Reykjavik',
            'Nur-Sułtan',
            'Vaduz',
            'Wilno',
            'Luksemburg',
            'Ryga',
            'Skopje',
            'Valleta',
            'Kiszyniów',
            'Monako',
            'Berlin',
            'Norwegoa',
            'Warszawa',
            'Lizbona',
            'Moskwa',
            'Bukareszt',
            'San Marino',
            'Belgrad',
            'Bratysława',
            'Lublana',
            'Berno',
            'Sztokholm',
            'Ankara',
            'Kijów',
            'Watykan',
            'Budapeszt',
            'Londyn',
            'Rzym',
        ]
    },
    {
        id: 11,
        question: "Wymień państwa Ameryki Południowej",
        avalibleAnswers: 13,
        answers: [
            'Argentyna',
            'Boliwia',
            'Brazylia',
            'Chile',
            'Ekwador',
            'Gujana',
            'Kolumbia',
            'Paragwaj',
            'Peru',
            'Surinam',
            'Trynidad i Tobago',
            'Urugwaj',
            'Wenezuela',
        ]
    }
]

export default questions;